# These are supported funding model platforms

github: nicholaschiasson
patreon: # Replace with a single Patreon username
open_collective: nicholaschiasson
ko_fi: nicholaschiasson
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: nicholaschiasson
issuehunt: nicholaschiasson
otechie: # Replace with a single Otechie username
custom: [buymeacoffee.com/nickyc]
