on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  preprocess:
    runs-on: ubuntu-latest
    container:
      image: node:14-alpine
    name: Preprocess
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Preprocess
        run: mkdir -p pre/rsrc/styles && npx tailwindcss -i rsrc/styles/tailwind.css -o pre/rsrc/styles/tailwind.css
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pre
          path: pre
  check:
    runs-on: ubuntu-latest
    container:
      image: rust:1.54
    name: Check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check
        run: rustup target add wasm32-unknown-unknown && cargo check --release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: target
  test:
    runs-on: ubuntu-latest
    container:
      image: rust:1.54
    name: Test
    needs: [check]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: target
          path: target
      - name: Test
        run: rustup target add wasm32-unknown-unknown && cargo test --release
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:1.54
    name: Build
    needs: [check, preprocess]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: pre
          path: pre
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: target
          path: target
      - name: Build
        run: cargo install --locked trunk && trunk build --release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  tag:
    runs-on: ubuntu-latest
    name: Tag
    needs: [build, check, preprocess, test]
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' && (success() || failure()) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check semver bump
        id: check-semver
        run: |
          if [[ "${{ github.event.head_commit.message }}" =~ ^Merge\ pull\ request\ #[0-9]+\ from\ [^/]+/patch/.+$ ]]; then
            echo ::set-output name=semver::patch
          elif [[ "${{ github.event.head_commit.message }}" =~ ^Merge\ pull\ request\ #[0-9]+\ from\ [^/]+/major/.+$ ]]; then
            echo ::set-output name=semver::major
          else
            echo ::set-output name=semver::minor
          fi
      - name: Bump major version and push tag
        if: ${{ steps.check-semver.outputs.semver == 'major' }}
        uses: anothrNick/github-tag-action@1.17.2
        env:
          DEFAULT_BUMP: major
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump minor version and push tag
        if: ${{ steps.check-semver.outputs.semver == 'minor' }}
        uses: anothrNick/github-tag-action@1.17.2
        env:
          DEFAULT_BUMP: minor
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump patch version and push tag
        if: ${{ steps.check-semver.outputs.semver == 'patch' }}
        uses: anothrNick/github-tag-action@1.17.2
        env:
          DEFAULT_BUMP: patch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
